### ISSUE TITLE
Allow disabling WebRTC support / Split HTTP(S) into an optional Cargo `feature`

### ISSUE THREAD

**Issue by Dessix** [naia-lib/naia#107]
It appears that `webrtc-unreliable-client` is not currently configurable as optional, and it adds quite a bit of overhead for native-only / non-WASM applications. Even if this is only for development purposes, reduced code-size by dropping WASM-aimed functionality can help with iteration time when working with something like Bevy.

**Comment by notverymoe** [comment]
I would strongly be in support of this change, it's what pushed me to chose Laminar over Naia despite preferring it.

This library requires extra steps for development on windows. Either installing OpenSSL or Perl and configuring the environment. The Perl option links OpenSSL statically, but adds a significant build size & time burden. As I have no intent for developing for web platforms with my current game I can't swallow the extra friction this creates on development. 

It being a feature would also be a boon for applications that target web and desktop, since it would improve build times and lower the barrier of entry for new developers on projects contributing on a windows machine.

**Comment by connorcarpenter** [comment]
In release 0.20, naia is now transport-agnostic, although it does export (under feature flags) some built-in WebRTC (using naia-socket) and UDP transports
