### ISSUE TITLE
Experiencing a lot of delay when running the bevy demo

### ISSUE THREAD

**Issue by NotHolst** [naia-lib/naia#140]
I have not changed anything in the demo, but i have what feels like almost 2 seconds of lag/delay. Running on Windows with a 5700x, low CPU usage

There's a chance I'm misunderstanding what exactly the demo is trying to convey, in that case please enlighten me :)

https://user-images.githubusercontent.com/7693663/220180269-3b536b2d-a7a9-4472-abd2-a5f9407a4cdc.mp4

**Comment by connorcarpenter** [comment]
Yep no worries, that does look a little slower than I'd predict, but it is in the ballpark of what I'd expect.

The Bevy demo currently runs default with the average-case LinkConditioner enabled:
https://github.com/naia-lib/naia/blob/8bb3c9179cd141aa52a2681ac564b3835181fc5d/demos/bevy/shared/src/protocol.rs#L12

That includes 200 ms of latency, 20 ms of jitter, and a 5.5% chance of packet loss. The client will run 3x the standard deviation of jitter so that 99.7% of packets arrive on time, so that's probably around the full 20ms.  Also it runs 1 full tick ahead of the server so in this case it's 25 ms more. So yeah, I'd expect 245 milliseconds of delay here.

**Comment by connorcarpenter** [comment]
Yep so there will be stutters/resyncs on the Bevy demo in `main` right now, as jitter/packet loss should occasionally cause input messages to be dropped, causing a client mis-predict, which is then reconciled by the client teleporting slightly to the authoritative position.

On top of that, you'll notice that even when removing the simulated packet loss / jitter, there may be some stutters. That's because, unlike client-side state which can "interpolate-on-the-fly" via things like delta time (i.e. https://bevy-cheatbook.github.io/features/time.html#delta-time), time in a Naia client is "quantized" not to the tick rate, but to the average tick duration of the Server. This allows the Client to adjust time on the fly if, say, the Server starts to run slower than the tick rate. However, at the millisecond-to-nanosecond level the tick rate should be constantly fluctuating.

I believe that all real-time networking models require some level of frame-interpolation on the client to reduce stutter of irregular incoming state updates. Naia is no exception. The Bevy demo currently doesn't include this interpolation, as there's many different possible strategies for this depending on your game and priorities. However, I plan to modify the demos soon to show off a working frame interpolation solution in the near future.

**Comment by connorcarpenter** [comment]
Now, if you're seeing some delay between keypress and white square movement in the demo ... that would be a problem. Interested to know if that's your experience :)

**Comment by NotHolst** [comment]
Thanks again for the explanation, judging by the amount of stutter i saw even on the average LinkConditioner I believe that they would be almost invisible with interpolation. Would be nice at some point to make a first-person demo to see how the packet loss feels there, event with interpolation.

In the Overwatch talk you linked he went over how they always send the last 15 frames or so of input, such that missed packages can be picked-up as long as they're within the buffer frame. Are you doing anything like this yet,  if not then i'd assume this would remove some of the jitter in movement ?

I fortunately did not experience any delay from keypress to initial movement :)

**Comment by connorcarpenter** [comment]
Yep Naia originally automatically implemented frame-interpolation way back but I removed it when realizing there were many use-cases where you'd want finer control of what and how everything interpolates. But my experience was that it looks super smooth.

And yeah, Naia's Tick Buffered Message Channels send all previous input that can possibly still be received by and processed by the server, every Tick. In average conditions the redundancy will be somewhat small however, as the number of times a command would be sent would be equal to ((jitter * 2) / tick rate) + 1.

I still need to implement some way for the Client to measure packet loss % in order to adjust it's own delay length to compensate for this (as explained in the Overwatch video)

**Comment by connorcarpenter** [comment]
I am going to close this issue as I believe NotHolst's questions have been answered (please re-open if not!) Thank you!
