### ISSUE TITLE
naia_shared depends on bevy_ecs

### ISSUE THREAD

**Issue by Madoshakalaka** [naia-lib/naia#74]
bevy_ecs appears in the naia-shared crate while it should only appear in the bevy adaptor crates?

**Comment by connorcarpenter** [comment]
That is what I would like as well, however, I could not figure out how to add `Replicate` structs to Bevy as components (requiring the `Component` trait) in an ergonomic way, due to the orphan rule ..

https://github.com/naia-lib/naia/blob/a8372c6853370e1f03c8a60895a7974631f51b5e/shared/src/protocol/replicate.rs#L66

And I'm not willing to have to wrap everything in a newtype in the Bevy adapter crates, would be such a headache for people I think. So an optional dependency on `bevy_ecs`, enabled only through the `bevy_support` feature flag, seemed like the least bad option I could find here ..

I would love it if someone else found a better solution :)

**Comment by Madoshakalaka** [comment]
oh, actually I didn't notice `bevy_ecs` was optional! It makes more sense now. I'll see if I can come up with anything, if anything at all :)
